name: Cygwin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - run: choco install -y cygwin

      - run: git config --global core.autocrlf input

      - uses: actions/checkout@v3
      
      - run: C:\tools\cygwin\bin\bash.exe --login -i -c "cd '${{ github.workspace }}' && bin/os"
