name: FreeBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-12

    strategy:
      fail-fast: false
      matrix:
        version: [13, 12]
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: vagrant-generic-freebsd-${{ matrix.version }}
          restore-keys: vagrant-generic-freebsd-${{ matrix.version }}

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: generic/freebsd${{ matrix.version }}
          run: run bin/os
