name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        version: [10.15, 11]

    runs-on: macos-${{ matrix.version }}

    steps:
    - uses: actions/checkout@v2
    
    - run: bin/os
