name: OpenBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-12
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: vagrant-generic-openbsd-6
          restore-keys: vagrant-generic-openbsd-6

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: generic/openbsd6
          run: run bin/os
