name: VoidLinux-glibc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    container: voidlinux/voidlinux

    steps:
      - uses: actions/checkout@v2

      - run: bin/os
